import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/beranda">Beranda</Link>
        </li>
        <li>
          <Link to="/kontak">Kontak</Link>
        </li>
        <li>
          <Link to="/masuk">Masuk</Link>
        </li>
        <li>
          <Link to="/bengkelprofile">BengkelProfile</Link>
        </li>
        <li>
          <Link to="/bengkelmontir">BengkelMontir</Link>
        </li>
        <li>
          <Link to="/bengkellayanan">BengkelLayanan</Link>
        </li>
        <li>
          <Link to="/bengkelpesanan">BengkelPesanan</Link>
        </li>
        <li>
          <Link to="/daftar">Daftar</Link>
        </li>
        <li>
          <Link to="/tentangkami">TentangKami</Link>
        </li>
        <li>
          <Link to="/montirprofil">Montirprofil</Link>
        </li>
        <li>
          <Link to="/montirpesanan">MontirPesanan</Link>
        </li>
        <li>
          <Link to="/setupakun">Setupakun</Link>
        </li>
        <li>
          <Link to="/adminbengkel">Adminbengkel</Link>
        </li>
        <li>
          <Link to="/adminmontir">AdminMontir</Link>
        </li>
        <li>
          <Link to="/adminedukasi">AdminEdukasi</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
